version: "3"
services:
  app:
    container_name: re-todo-app
    links:
      - redis
    depends_on:
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    tty: true
    volumes:
      - ./src:/go/src/app
    environment:
      REDIS_HOST: redis

  redis:
    container_name: re-todo-redis
    hostname: redis
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
    command: redis-server --appendonly yes

volumes:
  db-data:
    driver: local
  redis-data:
    driver: local
